### ISSUE TITLE
Incorrect `idToken` when using 3rd Auth Provider

### ISSUE THREAD

**Issue by PwnedC99** [soranoo/lovable-downloader#1]
How does one authenticate?

**Comment by soranoo** [comment]
Just log in and select a project from https://lovable.dev/ then the plugin will just work out of the box.

**Comment by PwnedC99** [comment]
Probably an issue when signing in with gmail, because it tells me that its not authenticated

**Comment by soranoo** [comment]
Ok I got it, lovable just upgraded to 2.0 the location of the API token has been moved. I will fix it ASAP

**Comment by soranoo** [comment]
Well, I realise they updated the site again and the plugin works again...

**Comment by PwnedC99** [comment]
Nope, still the same issue. Using Google to authenticate

**Comment by soranoo** [comment]
try to refresh the project page after entering the page from the main menu.

**Comment by PwnedC99** [comment]
When debugging I've noticed that it does not find the idToken. I guess it has something todo with the regex

**Comment by soranoo** [comment]
Ok, confirmed the jwt(id token) in accounts using 3rd auth are formed wrongly.

Temporary Solution:
Open an account using email and pw, then remix the project and download from it.

**Comment by PwnedC99** [comment]
one can fix the issue by replacing the line with idToken, with customToken: /\\"customToken\\":\\"([A...

https://github.com/soranoo/lovable-downloader/blob/58c4eecec1b37189e9452873026a2d63d7362982/chrome/content-script.js#L64

**Comment by PwnedC99** [comment]
nevermind, the token is for something else. anyone instead of the token in the "idToken" field it stores some placeholder.

**Comment by soranoo** [comment]
It should work now

**Comment by PwnedC99** [comment]
unfortunately still persists. authentication token not found

**Comment by soranoo** [comment]
Can I have a screenshot from the console.

**Comment by PwnedC99** [comment]
sure 

![Image](https://github.com/user-attachments/assets/a1899448-e292-4396-9773-21a2b10551ba)

**Comment by soranoo** [comment]
Can you update your tempermonkey script/Chrome extension to the latest release?

[Tempermonkey](https://github.com/soranoo/lovable-downloader/blob/main/tampermonkey/tampermonkey.js)
[Chrome Extension](https://github.com/soranoo/lovable-downloader/tree/main/chrome)

**Comment by soranoo** [comment]
Wait, my bad I didn't update the chrome extension

**Comment by soranoo** [comment]
> [!NOTE]\
> If you are logged in using 3rd party providers (eg. Google, GitHub), please check the in-page toolbar download button. The download button in the extension may not work as expected due to the inability to obtain the ID token.

Please update the extension to `1.1.0` and download with the in-page download buttons instead of the extension pop window button.

**Comment by PwnedC99** [comment]
![Image](https://github.com/user-attachments/assets/68e63d34-affe-41f2-8a1a-b3c1da5c3cfb)

says not authenticated / using 3rd party auth now but still does not find the element in the dom

**Comment by soranoo** [comment]
Can you see the inpage download btns?

![Image](https://github.com/user-attachments/assets/ca2c82b7-e5fa-498f-ab5d-e8dd697ec2ad)

**Comment by soranoo** [comment]
> ![Image](https://github.com/user-attachments/assets/68e63d34-affe-41f2-8a1a-b3c1da5c3cfb)
> 
> says not authenticated / using 3rd party auth now but still does not find the element in the dom

That is correct.

**Comment by soranoo** [comment]
As long as you see the in-page download buttons and download content via them, then everything is correct.

**Comment by PwnedC99** [comment]
works as expected, thanks!
